version: '2'
services:
  test-env:
    image: registry.makandra.de/rails-lts/rails-lts-docker/test-env
    depends_on:
      - mysql
      - postgres
      - memcached
    environment:
      BUNDLE_GEMFILE: /repo/Gemfile.1.8
      BUNDLE_PATH: /cache/bundle
      MYSQL_HOST: mysql-db
      MYSQL_USER: rails
      PG_HOST: pg-db
      PG_USER: rails
      MEMCACHE_HOST: memcached
      RBENV_VERSION: 1.8.7
      PROMPT: 'rails 2.3 : ruby 1.8.7'
    networks:
      - db
    volumes:
      - ../:/repo
      - cache:/cache
    working_dir: /repo
  mysql:
    image: registry.makandra.de/rails-lts/rails-lts-docker/mysql:5.6
    networks:
      db:
        aliases:
          - mysql-db
  postgres:
    image: registry.makandra.de/rails-lts/rails-lts-docker/pg:9.1
    networks:
      db:
        aliases:
          - pg-db
  memcached:
    image: registry.makandra.de/rails-lts/rails-lts-docker/memcached:1.5
    networks:
      db:
        aliases:
          - memcached

networks:
  db:


volumes:
  cache:
